# Generated by Django 6.0.7 on 2026-08-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperuserRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Резервный код супер-админа',
                'verbose_name_plural': 'Резервные коды супер-админа',
                'indexes': [models.Index(fields=['user', 'used_at'], name='accounts_rec_user_used_idx')],
            },
        ),
    ]
