# Generated by Django 6.0.8 on 2026-09-03 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_superuser_recovery_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=512, unique=True, verbose_name='ID credential (base64url)')),
                ('public_key', models.BinaryField(verbose_name='Публичный ключ (COSE)')),
                ('sign_count', models.PositiveIntegerField(default=0, verbose_name='Счётчик подписей')),
                ('device_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Название устройства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ключ доступа (passkey)',
                'verbose_name_plural': 'Ключи доступа (passkeys)',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pk_user_created_idx')],
            },
        ),
    ]
