# Generated by Django 6.0.8 on 2026-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passkey_credential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passkeycredential',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ключ доступа', 'verbose_name_plural': 'Ключи доступа'},
        ),
        migrations.AlterField(
            model_name='passkeycredential',
            name='credential_id',
            field=models.CharField(max_length=512, unique=True, verbose_name='Идентификатор ключа'),
        ),
        migrations.AlterField(
            model_name='passkeycredential',
            name='public_key',
            field=models.BinaryField(verbose_name='Публичный ключ'),
        ),
    ]
