# Generated by Django 6.0.8 on 2026-09-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passkey_verbose_ru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, default='', help_text='Числовой ID личного чата с ботом. В личке бота: /chatid — скопируйте ответ сюда.', max_length=64, verbose_name='Telegram chat ID')),
                ('telegram_alerts_enabled', models.BooleanField(default=True, help_text='Выкл — не слать личные уведомления этому сотруднику.', verbose_name='Telegram-алерты включены')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram сотрудника',
                'verbose_name_plural': 'Telegram сотрудников',
            },
        ),
    ]
