# Generated by Django 6.0.8 on 2026-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_telegram_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftelegramprofile',
            name='telegram_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Выкл — не слать личные уведомления этому сотруднику.', verbose_name='уведомления в Telegram включены'),
        ),
        migrations.AlterField(
            model_name='stafftelegramprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Числовой ID личного чата с ботом. В личке бота отправьте команду для получения ID и скопируйте ответ сюда.', max_length=64, verbose_name='ID чата Telegram'),
        ),
    ]
