# Generated by Django 6.1.1 on 2026-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff_max_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmaxprofile',
            name='max_user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Числовой идентификатор из личного чата с ботом. В боте отправьте /chatid и скопируйте ответ сюда.', max_length=64, verbose_name='ID пользователя в MAX'),
        ),
    ]
