# Generated by Django 6.1.1 on 2026-10-06 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_max_admin_ru_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_user', models.EmailField(blank=True, default='', help_text='Например ivan@hoocon.ru — совпадает с IMAP-логином.', max_length=254, verbose_name='адрес ящика')),
                ('imap_password', models.CharField(blank=True, default='', help_text='Яндекс 360: Пароль → Пароли приложений → Почта. Оставьте пустым — старый пароль сохранится.', max_length=200, verbose_name='пароль приложения IMAP')),
                ('folder', models.CharField(default='INBOX', max_length=100, verbose_name='папка')),
                ('is_enabled', models.BooleanField(default=True, help_text='Выкл — ящик не опрашивается фетчером.', verbose_name='сбор включён')),
                ('last_uid', models.PositiveBigIntegerField(default=0, verbose_name='последний обработанный UID')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='последний запуск')),
                ('last_error', models.CharField(blank=True, default='', max_length=300, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Почта сотрудника (IMAP)',
                'verbose_name_plural': 'Почта сотрудников (IMAP)',
            },
        ),
    ]
