# Generated by Django 6.1.1 on 2026-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffmailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmailbox',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.yandex.ru', help_text='Пусто — исходящие уходят через общий ящик. Логин и пароль те же, что у IMAP.', max_length=200, verbose_name='SMTP-сервер'),
        ),
        migrations.AddField(
            model_name='staffmailbox',
            name='smtp_port',
            field=models.PositiveSmallIntegerField(default=465, verbose_name='SMTP-порт'),
        ),
        migrations.AddField(
            model_name='staffmailbox',
            name='smtp_use_ssl',
            field=models.BooleanField(default=True, help_text='Вкл — SSL (порт 465), выкл — STARTTLS (порт 587).', verbose_name='SMTP по SSL'),
        ),
        migrations.AlterField(
            model_name='staffmailbox',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Выкл — ящик не опрашивается фетчером и не используется для отправки.', verbose_name='включён'),
        ),
    ]
