# Generated by Django 6.1.1 on 2026-10-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffmailbox_smtp_host_staffmailbox_smtp_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='эл. почта')),
                ('password_hash', models.CharField(blank=True, default='', help_text='Пусто — вход только по коду на почту или Яндекс ID.', max_length=200, verbose_name='хеш пароля')),
                ('auth_mode', models.CharField(choices=[('password', 'пароль'), ('otp_email', 'код на почту'), ('yandex', 'Яндекс ID')], default='password', max_length=20, verbose_name='способ входа')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='имя / контакт')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='телефон')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='OTP-вход или письмо-подтверждение; Яндекс ID подтверждает сам.', null=True, verbose_name='почта подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'аккаунт клиента',
                'verbose_name_plural': 'аккаунты клиентов',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=30, verbose_name='провайдер')),
                ('provider_user_id', models.CharField(max_length=200, verbose_name='id у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.clientaccount', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'соцпривязка клиента',
                'verbose_name_plural': 'соцпривязки клиентов',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='accounts_social_provider_uid_uniq')],
            },
        ),
    ]
