# Generated by Django 6.1.1 on 2026-10-07 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientaccount_socialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffVpbxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(blank=True, db_index=True, default='', help_text='Внутренний номер в Mango АТС — по нему звонок привязывается к менеджеру.', max_length=20, verbose_name='добавочный номер')),
                ('is_enabled', models.BooleanField(default=True, help_text='Выкл — звонки на этот добавочный не привязываются к сотруднику.', verbose_name='включён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpbx_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Добавочный сотрудника (Mango)',
                'verbose_name_plural': 'Добавочные сотрудников (Mango)',
            },
        ),
    ]
