# Generated by Django 6.1.2 on 2026-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staffvpbxprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmailbox',
            name='imap_password',
            field=models.CharField(blank=True, default='', help_text='Яндекс 360: Пароль → Пароли приложений → Почта. Оставьте пустым — старый пароль сохранится.', max_length=512, verbose_name='пароль приложения IMAP'),
        ),
    ]
