# Generated by Django 6.0.7 on 2026-07-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('sku_code', models.CharField(db_index=True, help_text='Артикул (уникален, не пуст), напр. HVA-5NM или BV215.', max_length=100, unique=True)),
                ('analog_belimo_code', models.CharField(blank=True, default=None, help_text='Код аналога Belimo (задел для AnalogMap P1).', max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена для КП менеджеру. В публичный API не утекает (см. SiteSettings.show_prices_on_site).', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Видимость SKU в публичном каталоге.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Продукт/линейка (обязательный). PROTECT — нельзя удалить.', on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.product')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'ordering': ('sku_code',),
            },
        ),
    ]
