# Generated by Django 6.0.7 on 2026-07-19 13:58

import catalog.models
import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_attribute_attributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(help_text='Только PDF; лимит и magic bytes — catalog.validators.', upload_to=catalog.models.product_file_upload_to, validators=[catalog.validators.validate_pdf_upload])),
                ('file_type', models.CharField(choices=[('datasheet', 'Паспорт / datasheet'), ('certificate', 'Сертификат'), ('catalog', 'Каталог'), ('other', 'Прочее')], db_index=True, default='datasheet', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Видимость файла в публичном каталоге / PDP.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Порядок в блоке «Документы» (меньше = выше).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(help_text='SKU, к которому привязан документ.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.sku')),
            ],
            options={
                'verbose_name': 'файл продукта',
                'verbose_name_plural': 'файлы продуктов',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
