# Generated by Django 6.0.7 on 2026-07-19 15:48

import catalog.models
import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sku_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='WebP предпочтительно; JPEG/PNG допустимы.', upload_to=catalog.models.product_image_upload_to, validators=[catalog.validators.validate_image_upload])),
                ('alt', models.CharField(blank=True, default='', max_length=300)),
                ('source_url', models.URLField(blank=True, default='', help_text='Исходный URL (Tilda CDN) для идемпотентного ETL.', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(help_text='SKU, к которому привязано фото.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.sku')),
            ],
            options={
                'verbose_name': 'изображение продукта',
                'verbose_name_plural': 'изображения продуктов',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('sku', 'source_url'), name='catalog_productimage_sku_source_url_uniq')],
            },
        ),
    ]
