# Generated by Django 6.0.7 on 2026-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Общая инструкция по монтажу/управлению для семейства.'),
        ),
        migrations.AddField(
            model_name='product',
            name='analogs_text',
            field=models.TextField(blank=True, default='', help_text='Аналоги линейки (до scoping по SKU).'),
        ),
        migrations.AddField(
            model_name='product',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Инструкция линейки (если отличается от категории).'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_text',
            field=models.TextField(blank=True, default='', help_text='Характеристики линейки (до scoping по SKU).'),
        ),
        migrations.AddField(
            model_name='sku',
            name='analogs_text',
            field=models.TextField(blank=True, default='', help_text='Аналоги для этого издания (артикула).'),
        ),
        migrations.AddField(
            model_name='sku',
            name='specs_text',
            field=models.TextField(blank=True, default='', help_text='Характеристики издания (напряжение/управление scoped).'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Общее описание семейства (для страницы категории).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание линейки (общее для всех изданий Product).'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание конкретной модели/издания для карточки.'),
        ),
    ]
