# Generated by Django 6.0.7 on 2026-07-20 12:06

import catalog.models
import catalog.validators
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_section_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ('sku_code',), 'verbose_name': 'артикул (SKU)', 'verbose_name_plural': 'артикулы (SKU)'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug (ключ)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='единица'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.attribute', verbose_name='атрибут'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=200, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Общее описание семейства (для страницы категории).', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Общая инструкция по монтажу/управлению для семейства.', verbose_name='инструкция'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительская категория (None для корня дерева).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='родитель'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug (URL)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='analogs_text',
            field=models.TextField(blank=True, default='', help_text='Аналоги линейки (до scoping по SKU).', verbose_name='аналоги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Категория товара (обязательная). PROTECT — нельзя удалить.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание линейки (общее для всех изданий Product).', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Инструкция линейки (если отличается от категории).', verbose_name='инструкция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs_text',
            field=models.TextField(blank=True, default='', help_text='Характеристики линейки (до scoping по SKU).', verbose_name='характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(help_text='Только PDF; лимит и magic bytes — catalog.validators.', upload_to=catalog.models.product_file_upload_to, validators=[catalog.validators.validate_pdf_upload], verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file_type',
            field=models.CharField(choices=[('datasheet', 'Паспорт'), ('certificate', 'Сертификат'), ('catalog', 'Каталог'), ('other', 'Прочее')], db_index=True, default='datasheet', max_length=20, verbose_name='тип файла'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Видимость файла в публичном каталоге / PDP.', verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='sku',
            field=models.ForeignKey(help_text='SKU, к которому привязан документ.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок в блоке «Документы» (меньше = выше).', verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='title',
            field=models.CharField(max_length=300, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='alt-текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='WebP предпочтительно; JPEG/PNG допустимы.', upload_to=catalog.models.product_image_upload_to, validators=[catalog.validators.validate_image_upload], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sku',
            field=models.ForeignKey(help_text='SKU, к которому привязано фото.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Исходный URL (Tilda CDN) для идемпотентного ETL.', max_length=500, verbose_name='исходный URL'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='analog_belimo_code',
            field=models.CharField(blank=True, default=None, help_text='Код аналога Belimo (задел для AnalogMap P1).', max_length=100, null=True, verbose_name='код аналога Belimo'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='analogs_text',
            field=models.TextField(blank=True, default='', help_text='Аналоги для этого издания (артикула).', verbose_name='аналоги'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание конкретной модели/издания для карточки.', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Видимость SKU в публичном каталоге.', verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=300, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена для КП менеджеру. В публичный API не утекает (см. SiteSettings.show_prices_on_site).', max_digits=10, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(help_text='Продукт/линейка (обязательный). PROTECT — нельзя удалить.', on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True, verbose_name='поисковый вектор'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(db_index=True, help_text='Артикул (уникален, не пуст), напр. HVA-5NM или BV215.', max_length=100, unique=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='slug (URL)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='specs_text',
            field=models.TextField(blank=True, default='', help_text='Характеристики издания (напряжение/управление scoped).', verbose_name='характеристики'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
