# Generated by Django 6.0.7 on 2026-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_audit_verbose_name_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='ключ фильтра'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='сегмент URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='сегмент URL'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='сегмент URL'),
        ),
    ]
