# Generated by Django 6.0.7 on 2026-07-21 06:59

import catalog.models
import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_admin_russian_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительская категория (пусто = корень дерева).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='родитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='analogs_text',
            field=models.TextField(blank=True, default='', help_text='Аналоги линейки (до уточнения по артикулу SKU).', verbose_name='аналоги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Категория товара (обязательная). Удалить категорию с товарами нельзя.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание линейки (общее для всех изданий продукта).', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs_text',
            field=models.TextField(blank=True, default='', help_text='Характеристики линейки (до уточнения по артикулу SKU).', verbose_name='характеристики'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(help_text='Только PDF; размер и тип файла проверяются при загрузке.', upload_to=catalog.models.product_file_upload_to, validators=[catalog.validators.validate_pdf_upload], verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Видимость файла в публичном каталоге и на карточке товара.', verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='sku',
            field=models.ForeignKey(help_text='Артикул (SKU), к которому привязан документ.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sku',
            field=models.ForeignKey(help_text='Артикул (SKU), к которому привязано фото.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Исходный URL (CDN Tilda) для повторного импорта без дублей.', max_length=500, verbose_name='исходный URL'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='analog_belimo_code',
            field=models.CharField(blank=True, default=None, help_text='Код аналога Belimo (для будущей карты аналогов).', max_length=100, null=True, verbose_name='код аналога Belimo'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена для КП менеджеру. В публичный API не попадает (см. настройку «показывать цены на сайте»).', max_digits=10, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(help_text='Продукт/линейка (обязательный). Удалить линейку с артикулами нельзя.', on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='specs_text',
            field=models.TextField(blank=True, default='', help_text='Характеристики издания (напряжение и управление — по артикулу).', verbose_name='характеристики'),
        ),
    ]
