# Generated by Django 6.0.7 on 2026-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_admin_ru_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Общее описание линейки продукции (для страницы категории).",
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Общая инструкция по монтажу/управлению для линейки продукции.",
                verbose_name="инструкция",
            ),
        ),
    ]
