# Generated by Django 6.0.7 on 2026-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_category_line_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='stock_qty',
            field=models.IntegerField(default=0, help_text='Количество на складе (из выгрузки 1С). На сайте только «есть / нет».', verbose_name='остаток'),
        ),
        migrations.AddField(
            model_name='sku',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Время последней загрузки остатков из выгрузки 1С.', null=True, verbose_name='остаток обновлён'),
        ),
    ]
