# Generated by Django 6.0.7 on 2026-08-04 20:11

import catalog.models
import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_sku_first_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_card",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="Лёгкий WebP для каталога/мобилок (генерируется из полного кадра).",
                upload_to=catalog.models.product_image_upload_to,
                validators=[catalog.validators.validate_image_upload],
                verbose_name="превью карточки",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="WebP предпочтительно; JPEG/PNG допустимы. Полный кадр (PDP).",
                upload_to=catalog.models.product_image_upload_to,
                validators=[catalog.validators.validate_image_upload],
                verbose_name="изображение",
            ),
        ),
    ]
