# Generated by Django 6.0.7 on 2026-08-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_productimage_image_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="stock_qty_ma",
            field=models.IntegerField(
                default=0,
                help_text=(
                    "Свободный остаток исполнений 4–20 мА (спецзаказ). В выгрузке 1С "
                    "это отдельная строка того же артикула с пометкой 4–20 мА. "
                    "На сайте только «есть / нет»."
                ),
                verbose_name="остаток 4–20 мА",
            ),
        ),
    ]
