# Generated by Django 6.0.8 on 2026-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_sku_stock_qty_ma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='Когда SKU впервые стал виден в публичном каталоге. Окно «Новое» — 30 суток; не путать с датами создания/обновления ETL.', null=True, verbose_name='впервые на сайте'),
        ),
    ]
