# Generated by Django 6.1.1 on 2026-10-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_sku_first_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, help_text='Напр. Belimo, Siemens, Danfoss.', max_length=100, verbose_name='сторонний бренд')),
                ('foreign_code', models.CharField(help_text='Как у производителя-аналога (регистр не важен).', max_length=100, verbose_name='артикул аналога')),
                ('foreign_code_key', models.CharField(db_index=True, editable=False, help_text='Нормализованный ключ совпадения (верхний регистр, без пробелов/дефисов).', max_length=100, verbose_name='ключ артикула')),
                ('torque_nm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='момент, Нм')),
                ('voltage', models.CharField(blank=True, default='', max_length=30, verbose_name='питание')),
                ('control', models.CharField(blank=True, default='', help_text='Напр. 3-точечное, 0-10В, 4-20мА.', max_length=50, verbose_name='управление')),
                ('spring_return', models.BooleanField(default=False, verbose_name='пружинный возврат')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='примечание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_maps', to='catalog.sku', verbose_name='наш артикул (SKU)')),
            ],
            options={
                'verbose_name': 'аналог стороннего артикула',
                'verbose_name_plural': 'карта аналогов',
                'ordering': ('brand', 'foreign_code'),
                'constraints': [models.UniqueConstraint(fields=('brand', 'foreign_code_key'), name='catalog_analogmap_brand_code_uniq')],
            },
        ),
    ]
