# Generated by Django 6.1.2 on 2026-10-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_analogmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Значение задано в админке: обогащение серии из мануала его не удаляет и не перезаписывает. Снимите галочку, чтобы вернуть канон.', verbose_name='правлено вручную'),
        ),
        migrations.AddField(
            model_name='product',
            name='copy_locked',
            field=models.BooleanField(default=False, help_text='Название и тексты правили в админке: обогащение серии из мануала их не перезаписывает. Ставится само при сохранении правок; снимите галочку, чтобы вернуть канон.', verbose_name='тексты правлены вручную'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='hidden_by_editor',
            field=models.BooleanField(default=False, help_text='Фото сняли с публикации в админке: аудит галереи и загрузка медиа его не возвращают. Снимается, если снова включить «опубликовано».', verbose_name='скрыто вручную'),
        ),
        migrations.AddField(
            model_name='sku',
            name='copy_locked',
            field=models.BooleanField(default=False, help_text='Название и тексты правили в админке: обогащение серии из мануала их не перезаписывает. Ставится само при сохранении правок; снимите галочку, чтобы вернуть канон.', verbose_name='тексты правлены вручную'),
        ),
    ]
