version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      poetry-patch-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
