# Generated by Django 6.0.7 on 2026-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, default='', help_text='Measurement ID вида G-XXXXXXXX. Пусто = не подключать.', max_length=32, verbose_name='ID Google Analytics 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата для бота MAX. Токен — MAX_BOT_TOKEN в .env.', max_length=64, verbose_name='MAX chat ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_enabled',
            field=models.BooleanField(default=False, verbose_name='MAX включён'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_announce_on_publish',
            field=models.BooleanField(default=False, help_text='При первой публикации статьи/новости отправить анонс во все включённые каналы (Celery).', verbose_name='автоанонс при публикации'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID канала/чата. Токен бота — TELEGRAM_BOT_TOKEN в .env.', max_length=64, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram включён'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_enabled',
            field=models.BooleanField(default=False, verbose_name='VK включён'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_group_id',
            field=models.CharField(blank=True, default='', help_text='Числовой ID сообщества (без минуса). Токен — VK_ACCESS_TOKEN в .env.', max_length=32, verbose_name='VK group ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, default='', help_text='Числовой ID счётчика (напр. 12345678). Пусто = не подключать.', max_length=32, verbose_name='ID Яндекс.Метрики'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_prices_on_site',
            field=models.BooleanField(default=False, help_text='Показывать цены в публичном API/UI. По умолчанию False — цены скрыты (политика RFQ). См. docs/security-baseline.md §3.2.', verbose_name='показывать цены на сайте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
