# Generated by Django 6.0.7 on 2026-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_analytics_and_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота MAX. Пустое поле при сохранении не стирает токен. Запасной вариант: MAX_BOT_TOKEN в .env.', max_length=500, verbose_name='MAX bot token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота (@BotFather). Пустое поле при сохранении не стирает уже сохранённый токен. Запасной вариант: TELEGRAM_BOT_TOKEN в .env.', max_length=200, verbose_name='Telegram bot token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_access_token',
            field=models.CharField(blank=True, default='', help_text='Ключ сообщества с правом wall. Пустое поле при сохранении не стирает токен. Запасной вариант: VK_ACCESS_TOKEN в .env.', max_length=500, verbose_name='VK access token'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата для бота MAX.', max_length=64, verbose_name='MAX chat ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID канала или чата (напр. -100… или @channel).', max_length=64, verbose_name='Telegram chat / channel ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vk_group_id',
            field=models.CharField(blank=True, default='', help_text='Числовой ID сообщества (без минуса).', max_length=32, verbose_name='VK group ID'),
        ),
    ]
