# Generated by Django 6.0.7 on 2026-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_social_bot_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, default='', help_text='Идентификатор вида G-XXXXXXXX. Пусто = не подключать.', max_length=32, verbose_name='идентификатор Google Analytics 4'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота MAX. Пустое поле при сохранении не стирает токен. Запасной вариант: MAX_BOT_TOKEN в .env.', max_length=500, verbose_name='токен бота MAX'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата для бота MAX.', max_length=64, verbose_name='ID чата MAX'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота (@BotFather). Пустое поле при сохранении не стирает уже сохранённый токен. Запасной вариант: TELEGRAM_BOT_TOKEN в .env.', max_length=200, verbose_name='токен бота Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID канала или чата (напр. -100… или @channel).', max_length=64, verbose_name='ID чата / канала Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vk_access_token',
            field=models.CharField(blank=True, default='', help_text='Ключ сообщества с правом wall. Пустое поле при сохранении не стирает токен. Запасной вариант: VK_ACCESS_TOKEN в .env.', max_length=500, verbose_name='токен доступа VK'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vk_group_id',
            field=models.CharField(blank=True, default='', help_text='Числовой ID сообщества (без минуса).', max_length=32, verbose_name='ID сообщества VK'),
        ),
    ]
