# Generated by Django 6.0.7 on 2026-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_admin_russian_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='max_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота MAX. Пустое поле при сохранении не стирает токен. Запасной вариант: MAX_BOT_TOKEN в файле окружения.', max_length=500, verbose_name='токен бота MAX'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_prices_on_site',
            field=models.BooleanField(default=False, help_text='Показывать цены в публичном API и на сайте. По умолчанию выкл. — цены скрыты (политика RFQ).', verbose_name='показывать цены на сайте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_announce_on_publish',
            field=models.BooleanField(default=False, help_text='При первой публикации статьи/новости отправить анонс во все включённые каналы (фоновая очередь).', verbose_name='автоанонс при публикации'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота (@BotFather). Пустое поле при сохранении не стирает уже сохранённый токен. Запасной вариант: TELEGRAM_BOT_TOKEN в файле окружения.', max_length=200, verbose_name='токен бота Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID канала или чата (напр. -100… или @имя_канала).', max_length=64, verbose_name='ID чата / канала Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vk_access_token',
            field=models.CharField(blank=True, default='', help_text='Ключ сообщества с правом публикации на стене. Пустое поле при сохранении не стирает токен. Запасной вариант: VK_ACCESS_TOKEN в файле окружения.', max_length=500, verbose_name='токен доступа VK'),
        ),
    ]
