# Generated by Django 6.0 on 2026-07-29

from django.db import migrations

PROD_YANDEX_METRIKA_ID = "73321399"
PROD_GA4_MEASUREMENT_ID = "G-DLRV7BZ5JP"


def fill_analytics_ids(apps, schema_editor):
    """Set production counter IDs when Admin fields are still empty."""
    SiteSettings = apps.get_model("sitesettings", "SiteSettings")
    obj, _created = SiteSettings.objects.get_or_create(pk=1)
    changed = False
    if not (obj.yandex_metrika_id or "").strip():
        obj.yandex_metrika_id = PROD_YANDEX_METRIKA_ID
        changed = True
    if not (obj.ga4_measurement_id or "").strip():
        obj.ga4_measurement_id = PROD_GA4_MEASUREMENT_ID
        changed = True
    if changed:
        obj.save()


def noop_reverse(apps, schema_editor):
    """Keep IDs on reverse — clearing would break prod analytics."""


class Migration(migrations.Migration):
    dependencies = [
        ("sitesettings", "0005_admin_ru_help_text"),
    ]

    operations = [
        migrations.RunPython(fill_analytics_ids, noop_reverse),
    ]
