# Generated by Django 6.0.7 on 2026-08-06 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0007_alter_sitesettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lead_routing_mode',
            field=models.CharField(
                choices=[
                    ("off", "Выкл — всё на общий ящик отдела продаж, без автоназначения"),
                    (
                        "assign_sales",
                        "Назначать менеджеру, письмо на общий ящик отдела продаж",
                    ),
                    ("assign_manager", "Назначать менеджеру, письмо менеджеру"),
                ],
                default="off",
                help_text=(
                    "Пул — активные сотрудники группы «Менеджер» с адресом в "
                    "профиле (логин). Выкл: письмо на LEAD_NOTIFY_EMAIL, без "
                    "назначения. «Назначать…»: равномерная очередь; при одном "
                    "менеджере всегда он. Пустой пул = как Выкл."
                ),
                max_length=32,
                verbose_name="распределение заявок",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="lead_rr_last_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Курсор очереди распределения (служебное; меняется автоматически).",
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="последний назначенный в очереди",
            ),
        ),
    ]
