# Generated by Django 6.0.7 on 2026-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0008_lead_routing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='lead_routing_mode',
            field=models.CharField(choices=[('off', 'Выкл — всё на общий ящик отдела продаж, без автоназначения'), ('assign_sales', 'Назначать менеджеру, письмо на общий ящик отдела продаж'), ('assign_manager', 'Назначать менеджеру, письмо менеджеру')], default='off', help_text='Пул — только сотрудники группы «Менеджер» со статусом «Активен», статусом персонала и адресом в профиле (логин). Неактивные в очередь и письма не попадают. Выкл: письмо на LEAD_NOTIFY_EMAIL, без назначения. «Назначать…»: равномерная очередь; при одном менеджере всегда он. Пустой пул = как Выкл.', max_length=32, verbose_name='распределение заявок'),
        ),
    ]
