# Generated by Django 6.0.8 on 2026-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0010_enable_assign_manager_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='staff_push_lead_body',
            field=models.CharField(blank=True, default='{name}: {lead_type}', help_text='Плейсхолдеры: {name}, {lead_type}. Пусто = шаблон по умолчанию.', max_length=200, verbose_name='текст push: заявка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_push_lead_title',
            field=models.CharField(blank=True, default='Новая заявка', help_text='Пусто = «Новая заявка».', max_length=80, verbose_name='заголовок push: заявка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_push_leads_enabled',
            field=models.BooleanField(default=True, help_text='Web Push в Admin PWA при новой заявке / консультации / замене. Персонал должен включить Push у себя (список заявок или «Ещё»).', verbose_name='push при новой заявке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_push_support_body',
            field=models.CharField(blank=True, default='{label}: новое обращение', help_text='Плейсхолдер: {label} (имя или канал). Пусто = шаблон по умолчанию.', max_length=200, verbose_name='текст push: поддержка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_push_support_enabled',
            field=models.BooleanField(default=True, help_text='Web Push в Admin PWA при входящем сообщении в чате поддержки.', verbose_name='push при сообщении в поддержке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_push_support_title',
            field=models.CharField(blank=True, default='Новое сообщение в поддержке', help_text='Пусто = «Новое сообщение в поддержке».', max_length=80, verbose_name='заголовок push: поддержка'),
        ),
    ]
