# Generated by Django 6.0.8 on 2026-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0011_staff_push_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='staff_telegram_leads_enabled',
            field=models.BooleanField(default=True, help_text='Личные сообщения бота менеджерам (группа «Менеджер») и супер-админам. Нужен chat ID в карточке пользователя (/chatid в боте).', verbose_name='Telegram при новой заявке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_telegram_superuser_crm_enabled',
            field=models.BooleanField(default=True, help_text='Смена статуса/ответственного заявки, ответ staff в чате, заметки CRM с автором — только супер-админам.', verbose_name='Telegram супер-админу по CRM'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_telegram_support_enabled',
            field=models.BooleanField(default=True, help_text='Входящий чат → менеджеры и супер-админы с привязанным Telegram.', verbose_name='Telegram при сообщении в поддержке'),
        ),
    ]
