# Generated by Django 6.0.8 on 2026-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0012_staff_telegram_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_telegram_leads_enabled',
            field=models.BooleanField(default=True, help_text='Только если у сотрудника нет активного Admin Web Push. Почта по заявкам — всегда; Push — доп. канал. Нужен chat ID (/chatid).', verbose_name='Telegram при новой заявке (если нет Push)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_telegram_superuser_crm_enabled',
            field=models.BooleanField(default=True, help_text='Статус/ответственный, ответ staff в чате, заметки CRM — супер-админам без активного Web Push.', verbose_name='Telegram супер-админу по CRM (если нет Push)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_telegram_support_enabled',
            field=models.BooleanField(default=True, help_text='Входящий чат → Telegram только без Web Push. Почта на первое обращение — отдельно.', verbose_name='Telegram при сообщении в поддержке (если нет Push)'),
        ),
    ]
