# Generated by Django 6.0.8 on 2026-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0013_staff_telegram_fallback_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_push_lead_body',
            field=models.CharField(blank=True, default='{имя}: {тип}', help_text='Подстановки в фигурных скобках: имя, тип. Пусто = шаблон по умолчанию.', max_length=200, verbose_name='текст уведомления: заявка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_push_lead_title',
            field=models.CharField(blank=True, default='Новая заявка', help_text='Пусто = «Новая заявка».', max_length=80, verbose_name='заголовок уведомления: заявка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_push_leads_enabled',
            field=models.BooleanField(default=True, help_text='Браузерные уведомления в установленном приложении админки при новой заявке / консультации / замене. Сотрудник включает их у себя (список заявок или «Ещё»).', verbose_name='уведомления на устройство при новой заявке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_push_support_body',
            field=models.CharField(blank=True, default='{метка}: новое обращение', help_text='Подстановка в фигурных скобках: метка (имя или канал). Пусто = шаблон по умолчанию.', max_length=200, verbose_name='текст уведомления: поддержка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_push_support_enabled',
            field=models.BooleanField(default=True, help_text='Браузерные уведомления в админке при входящем сообщении в чате поддержки.', verbose_name='уведомления на устройство при сообщении в поддержке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_push_support_title',
            field=models.CharField(blank=True, default='Новое сообщение в поддержке', help_text='Пусто = «Новое сообщение в поддержке».', max_length=80, verbose_name='заголовок уведомления: поддержка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_telegram_leads_enabled',
            field=models.BooleanField(default=True, help_text='Личные сообщения бота, только если у сотрудника нет активных браузерных уведомлений админки. Почта по заявкам — всегда; уведомления на устройстве — доп. канал. Нужен ID чата (команда бота).', verbose_name='Telegram при новой заявке (если нет уведомлений на устройстве)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_telegram_superuser_crm_enabled',
            field=models.BooleanField(default=True, help_text='Статус/ответственный, ответ сотрудника в чате, заметки CRM — супер-админам без активных браузерных уведомлений.', verbose_name='Telegram супер-админу по CRM (если нет уведомлений на устройстве)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_telegram_support_enabled',
            field=models.BooleanField(default=True, help_text='Входящий чат → Telegram только без браузерных уведомлений. Почта на первое обращение — отдельно.', verbose_name='Telegram при сообщении в поддержке (если нет уведомлений на устройстве)'),
        ),
    ]
