# Generated by Django 6.1.1 on 2026-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0015_staff_max_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_max_leads_enabled',
            field=models.BooleanField(default=True, help_text='Личные сообщения бота при новой заявке (RFQ / консультация / замена). Нужен ID в карточке сотрудника (/chatid в боте).', verbose_name='MAX при новой заявке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_max_support_enabled',
            field=models.BooleanField(default=True, help_text='Входящее сообщение в чат поддержки → личный MAX менеджерам с привязанным ID пользователя.', verbose_name='MAX при сообщении в поддержке'),
        ),
    ]
