# Generated by Django 6.1.1 on 2026-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0017_gigachat_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='gigachat_enabled',
            field=models.BooleanField(default=False, help_text='Первичные ответы в support-чате через GigaChat API. По умолчанию режим triage (приветствие, без консультаций по продукции). Нужен Authorization Key (Admin или GIGACHAT_CREDENTIALS в .env).', verbose_name='GigaChat-ассистент в чате'),
        ),
    ]
