# Generated by Django 6.1.1 on 2026-10-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0018_alter_sitesettings_gigachat_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_mode',
            field=models.CharField(blank=True, choices=[('', 'по умолчанию (GIGACHAT_MODE из .env)'), ('triage', 'Первичный приём — без консультаций по продукции'), ('full', 'Полный — ответы по базе знаний сайта и мануалам')], default='', help_text='«Первичный приём»: бот только приветствует, уточняет и передаёт менеджеру. «Полный»: бот отвечает по мануалам и контенту сайта. Пусто — GIGACHAT_MODE из .env.', max_length=16, verbose_name='режим ассистента'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ai_max_turns',
            field=models.PositiveSmallIntegerField(default=10, help_text='После N ответов бота диалог передаётся менеджеру.', verbose_name='лимит ответов ассистента'),
        ),
    ]
