# Generated by Django 6.1.1 on 2026-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0019_sitesettings_ai_mode_alter_sitesettings_ai_max_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cabinet_enabled',
            field=models.BooleanField(default=False, help_text='Выкл — API кабинета (/api/auth/*, /api/account/*) отдаёт 404 и предложение создать кабинет после заявки не показывается. Включить после выкатки, когда кабинет готов к клиентам.', verbose_name='личный кабинет клиента'),
        ),
    ]
