# Generated by Django 6.1.2 on 2026-10-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0020_sitesettings_cabinet_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='rop_report_email',
            field=models.CharField(blank=True, default='', help_text='Куда слать еженедельный отчёт по работе менеджеров. Несколько адресов через запятую. Пусто — LEAD_NOTIFY_EMAIL (общий ящик отдела).', max_length=500, verbose_name='почта отчёта РОП'),
        ),
    ]
