# Generated by Django 6.1.1 on 2026-10-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_clientaccount_socialaccount'),
        ('catalog', '0017_alter_sku_first_published_at'),
        ('crm', '0009_quote_quoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, verbose_name='номер заказа / счёта')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('shipped', 'Отгружен'), ('done', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='accepted', max_length=20, verbose_name='статус')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Опционально, 0–100.', verbose_name='готовность, %')),
                ('planned_ship_date', models.DateField(blank=True, null=True, verbose_name='плановая отгрузка')),
                ('carrier', models.CharField(blank=True, choices=[('', '—'), ('dl', 'Деловые Линии'), ('sdek', 'СДЭК'), ('pek', 'ПЭК'), ('other', 'Другая')], default='', max_length=20, verbose_name='транспортная компания')),
                ('track_number', models.CharField(blank=True, default='', max_length=100, verbose_name='трек-номер ТК')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='Задел под синк с 1С:УНФ (пока не интегрируем).', max_length=100, verbose_name='id документа УНФ')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.client', verbose_name='клиент')),
                ('quote', models.ForeignKey(blank=True, help_text='Согласованное КП, из которого вырос заказ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.quote', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', max_length=100, verbose_name='код артикула')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Только Admin; клиенту цены видны в PDF счёта.', max_digits=12, null=True, verbose_name='цена за ед., ₽')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cabinet.order', verbose_name='заказ')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.sku', verbose_name='артикул (SKU)')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RmaCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='серийный номер')),
                ('subject', models.CharField(max_length=300, verbose_name='тема')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание проблемы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('resolved', 'Решена')], db_index=True, default='new', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_cases', to='crm.client', verbose_name='клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_cases', to='cabinet.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'рекламация (RMA)',
                'verbose_name_plural': 'рекламации (RMA)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название набора')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_lists', to='accounts.clientaccount', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'спецификация',
                'verbose_name_plural': 'спецификации',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', help_text='Снимок кода — переживает удаление SKU.', max_length=100, verbose_name='код артикула')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_list_items', to='catalog.sku', verbose_name='артикул (SKU)')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cabinet.speclist', verbose_name='спецификация')),
            ],
            options={
                'verbose_name': 'позиция спецификации',
                'verbose_name_plural': 'позиции спецификаций',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('client', 'number'), name='account_order_client_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='speclist',
            index=models.Index(fields=['account', '-updated_at'], name='account_spec_acct_upd_idx'),
        ),
    ]
