# Generated by Django 6.1.1 on 2026-10-06 18:20

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='photo',
            field=models.ImageField(blank=True, default='', help_text='Приватное хранилище; скачивание только владельцем и персоналом.', storage=cabinet.models._private_media_storage, upload_to=cabinet.models.rma_photo_upload_to, verbose_name='фото дефекта'),
        ),
    ]
