# Generated by Django 6.0.7 on 2026-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('body', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Видимость в публичном API.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); null = черновик.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('-published_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('body', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Видимость в публичном API.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); null = черновик.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-published_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('body', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Видимость в публичном API.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); null = черновик.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'ordering': ('-published_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
