# Generated by Django 6.0.7 on 2026-07-19 16:46

import catalog.validators
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_search_vector_news_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='Обложка статьи (JPEG/PNG/WebP).', null=True, upload_to=content.models.article_cover_upload_to, validators=[catalog.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Краткий анонс для списка /statyi (без HTML).'),
        ),
    ]
