# Generated by Django 6.0.7 on 2026-07-19 19:09

import catalog.validators
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_page_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, help_text='Обложка новости (JPEG/PNG/WebP).', null=True, upload_to=content.models.news_cover_upload_to, validators=[catalog.validators.validate_image_upload]),
        ),
    ]
