# Generated by Django 6.0.7 on 2026-07-20 12:06

import catalog.validators
import content.models
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_news_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='Обложка статьи (JPEG/PNG/WebP).', null=True, upload_to=content.models.article_cover_upload_to, validators=[catalog.validators.validate_image_upload], verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Краткий анонс для списка /statyi (без HTML).', verbose_name='анонс'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Видимость в публичном API.', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); null = черновик.', null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True, verbose_name='поисковый вектор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='slug (URL)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, help_text='Обложка новости (JPEG/PNG/WebP).', null=True, upload_to=content.models.news_cover_upload_to, validators=[catalog.validators.validate_image_upload], verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Видимость в публичном API.', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); null = черновик.', null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True, verbose_name='поисковый вектор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='slug (URL)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Видимость в публичном API.', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); null = черновик.', null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='page',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True, verbose_name='поисковый вектор'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='slug (URL)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=300, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
