# Generated by Django 6.0.7 on 2026-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_audit_verbose_name_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='сегмент URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='сегмент URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='сегмент URL'),
        ),
    ]
