# Generated by Django 6.0.7 on 2026-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_admin_russian_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Краткий анонс для списка статей (без HTML).', verbose_name='анонс'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); пусто = черновик.', null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); пусто = черновик.', null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата публикации (для сортировки/SEO); пусто = черновик.', null=True, verbose_name='дата публикации'),
        ),
    ]
