# Generated by Django 6.0.7 on 2026-08-05 21:26

import catalog.validators
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_company_warranty_24_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_dark",
            field=models.ImageField(
                blank=True,
                help_text="Обложка для тёмной темы (JPEG/PNG/WebP → WebP). Пусто = как светлая.",
                null=True,
                upload_to=content.models.article_cover_upload_to,
                validators=[catalog.validators.validate_image_upload],
                verbose_name="обложка (тёмная тема)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Обложка для светлой темы (JPEG/PNG/WebP → WebP).",
                null=True,
                upload_to=content.models.article_cover_upload_to,
                validators=[catalog.validators.validate_image_upload],
                verbose_name="обложка",
            ),
        ),
    ]
