# Generated by Django 6.0.7 on 2026-08-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_article_cover_dark'),
        ('content', '0012_news_launch_br_adapters'),
    ]

    operations = [
    ]
