# Generated by Django 6.1.2 on 2026-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_wikidocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidocument',
            name='seed_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='sha256 HTML из репозитория на момент последнего сида; иначе — правка в админке.', max_length=64, verbose_name='хэш сида'),
        ),
    ]
