/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List categories with a product preview image per row. */
        get: operations["catalog_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/compare/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return SKU columns and highlight matrix rows. */
        get: operations["catalog_compare_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/facets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return canonical facets for the catalog filter UI. */
        get: operations["catalog_facets_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/skus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/catalog/skus/ and /api/catalog/skus/{slug}/. */
        get: operations["catalog_skus_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/skus/{sku_slug}/files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET (public) + POST (staff) /api/catalog/skus/{sku_slug}/files/. */
        get: operations["catalog_skus_files_list"];
        put?: never;
        /** @description Upload a PDF to the SKU identified by sku_slug in the URL. */
        post: operations["catalog_skus_files_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/skus/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/catalog/skus/ and /api/catalog/skus/{slug}/. */
        get: operations["catalog_skus_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/articles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/articles/ and /api/content/articles/{slug}/. */
        get: operations["content_articles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/articles/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/articles/ and /api/content/articles/{slug}/. */
        get: operations["content_articles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/news/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/news/ and /api/content/news/{slug}/. */
        get: operations["content_news_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/news/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/news/ and /api/content/news/{slug}/. */
        get: operations["content_news_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/pages/ and /api/content/pages/{slug}/. */
        get: operations["content_pages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/pages/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/pages/ and /api/content/pages/{slug}/. */
        get: operations["content_pages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Return JSON {csrfToken} and set the csrftoken cookie.
         *
         *     Args:
         *         request: DRF request.
         *
         *     Returns:
         *         200 with {"csrfToken": "<token>"}.
         */
        get: operations["csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/telegram/webhook/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accept a Telegram Update and optionally reply to a command. */
        post: operations["integrations_telegram_webhook_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Handle POST: validate, honeypot check, create, schedule email.
         *
         *     Args:
         *         request: DRF request with lead payload.
         *
         *     Returns:
         *         201 with serialized lead (PII-safe: no email/phone in response),
         *         or 201 silent drop if honeypot is filled (no lead created),
         *         or 400 on validation errors.
         */
        post: operations["leads_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Handle GET: parse `q`, run FTS on all content models, paginate.
         *
         *     Args:
         *         request: DRF request with optional `q` query parameter.
         *
         *     Returns:
         *         200 with paginated results: {count, next, previous, results}.
         *         Each result: {type, slug, title, url, snippet}.
         */
        get: operations["search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/public/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Return Yandex Metrika / GA4 IDs from SiteSettings with env defaults.
         *
         *     Args:
         *         request: unused DRF request.
         *
         *     Returns:
         *         JSON with yandex_metrika_id and ga4_measurement_id (may be empty).
         */
        get: operations["settings_public_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Article detail: list fields + SKUs mentioned in the text. */
        Article: {
            readonly id: number;
            /** Заголовок */
            readonly title: string;
            /** Сегмент URL */
            readonly slug: string;
            /**
             * Анонс
             * @description Краткий анонс для списка статей (без HTML).
             */
            readonly excerpt: string;
            /** Format: uri */
            readonly cover: string | null;
            /** Format: uri */
            readonly cover_dark: string | null;
            /** Текст */
            readonly body: string;
            /**
             * Опубликовано
             * @description Видимость в публичном API.
             */
            readonly is_published: boolean;
            /**
             * Дата публикации
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); пусто = черновик.
             */
            readonly published_at: string | null;
            /**
             * Создано
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлено
             * Format: date-time
             */
            readonly updated_at: string;
            /** @description Return catalog cards for models referenced in the article. */
            readonly related_skus: {
                [key: string]: unknown;
            }[];
        };
        /** @description Article card for /statyi list (no related SKUs). */
        ArticleList: {
            readonly id: number;
            /** Заголовок */
            readonly title: string;
            /** Сегмент URL */
            readonly slug: string;
            /**
             * Анонс
             * @description Краткий анонс для списка статей (без HTML).
             */
            readonly excerpt: string;
            /** Format: uri */
            readonly cover: string | null;
            /** Format: uri */
            readonly cover_dark: string | null;
            /** Текст */
            readonly body: string;
            /**
             * Опубликовано
             * @description Видимость в публичном API.
             */
            readonly is_published: boolean;
            /**
             * Дата публикации
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); пусто = черновик.
             */
            readonly published_at: string | null;
            /**
             * Создано
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлено
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** @description Public category list/detail fields (series overview + install). */
        Category: {
            readonly id: number;
            /** Название */
            readonly name: string;
            /** Сегмент URL */
            readonly slug: string;
            /**
             * Родитель
             * @description Родительская категория (пусто = корень дерева).
             */
            readonly parent: number | null;
            /**
             * Описание
             * @description Общее описание линейки продукции (для страницы категории).
             */
            readonly description: string;
            /**
             * Инструкция
             * @description Общая инструкция по монтажу/управлению для линейки продукции.
             */
            readonly instructions: string;
            /** @description First published product photo in this category (homepage tiles). */
            readonly image: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description * `datasheet` - Паспорт
         *     * `certificate` - Сертификат
         *     * `catalog` - Каталог
         *     * `other` - Прочее
         * @enum {string}
         */
        FileTypeEnum: "datasheet" | "certificate" | "catalog" | "other";
        /**
         * @description Serializer for public Lead creation (RFQ / consultation / replacement).
         *
         *     Only client-facing fields are writable; status/timestamps are read-only.
         *     `email` and `phone` are write-only (PII-safe response). `website` is a
         *     honeypot field — the view silently drops submissions where it's filled.
         */
        Lead: {
            readonly id: number;
            /** Тип заявки */
            lead_type?: components["schemas"]["LeadTypeEnum"];
            /** Имя */
            name: string;
            /**
             * Эл. почта
             * Format: email
             */
            email: string;
            /** Телефон */
            phone?: string;
            /** Компания */
            company?: string;
            /** Сообщение */
            message: string;
            /** Сегмент URL */
            sku?: string | null;
            /**
             * Количество
             * @description Количество позиций в запросе КП (RFQ).
             */
            quantity?: number | null;
            /**
             * Код аналога Belimo
             * @description Код аналога Belimo (для заявок на замену).
             */
            analog_belimo_code?: string;
            /** Статус */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * Создано
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлено
             * Format: date-time
             */
            readonly updated_at: string;
            /**
             * @description Honeypot — leave empty (hidden from real users).
             * @default
             */
            website: string;
        };
        /**
         * @description * `rfq` - Запрос КП
         *     * `consultation` - Консультация
         *     * `replacement` - Подбор замены
         * @enum {string}
         */
        LeadTypeEnum: "rfq" | "consultation" | "replacement";
        /** @description Company news item (/novosti/<slug>). */
        News: {
            readonly id: number;
            /** Заголовок */
            readonly title: string;
            /** Сегмент URL */
            readonly slug: string;
            /** Текст */
            readonly body: string;
            /** Format: uri */
            readonly cover: string | null;
            /**
             * Опубликовано
             * @description Видимость в публичном API.
             */
            readonly is_published: boolean;
            /**
             * Дата публикации
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); пусто = черновик.
             */
            readonly published_at: string | null;
            /**
             * Создано
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлено
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** @description Public CMS page (/<slug>). */
        Page: {
            readonly id: number;
            /** Заголовок */
            readonly title: string;
            /** Сегмент URL */
            readonly slug: string;
            /** Текст */
            readonly body: string;
            /**
             * Опубликовано
             * @description Видимость в публичном API.
             */
            readonly is_published: boolean;
            /**
             * Дата публикации
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); пусто = черновик.
             */
            readonly published_at: string | null;
            /**
             * Создано
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Обновлено
             * Format: date-time
             */
            readonly updated_at: string;
        };
        PaginatedArticleListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ArticleList"][];
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedNewsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["News"][];
        };
        PaginatedPageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Page"][];
        };
        PaginatedProductFileUploadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProductFileUpload"][];
        };
        PaginatedSKUListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SKUList"][];
        };
        /** @description Serializer for staff upload (POST) and public read (GET). */
        ProductFileUpload: {
            readonly id: number;
            /** Название */
            title: string;
            /**
             * Файл
             * Format: uri
             * @description Только PDF; размер и тип файла проверяются при загрузке.
             */
            file: string;
            /** Тип файла */
            file_type?: components["schemas"]["FileTypeEnum"];
            /**
             * Опубликован
             * @description Видимость файла в публичном каталоге и на карточке товара.
             */
            is_published?: boolean;
            /**
             * Порядок
             * @description Порядок в блоке «Документы» (меньше = выше).
             */
            sort_order?: number;
        };
        /** @description SKU PDP payload: list fields + sectioned copy + attributes + files. */
        SKUDetail: {
            readonly id: number;
            /** @description H1/card title: series Product name on family list cards, else edition. */
            readonly name: string;
            /** Сегмент URL */
            readonly slug: string;
            /**
             * Артикул
             * @description Артикул (уникален, не пуст), напр. HVA-5NM или BV215.
             */
            readonly sku_code: string;
            /**
             * Код аналога Belimo
             * @description Код аналога Belimo (для будущей карты аналогов).
             */
            readonly analog_belimo_code: string | null;
            readonly category_slug: string;
            readonly product_slug: string;
            /**
             * Цена
             * Format: decimal
             * @description Цена для КП менеджеру. В публичный API не попадает (см. настройку «показывать цены на сайте»).
             */
            readonly price: string | null;
            /** @description True when prices are hidden (RFQ policy). */
            readonly price_on_request: boolean;
            /** @description True when warehouse quantity is positive (no raw qty in public API). */
            readonly in_stock: boolean;
            /** @description True when first_published_at is within the Новинки window (30 days). */
            readonly is_new: boolean;
            /**
             * Впервые на сайте
             * Format: date-time
             * @description Когда SKU впервые стал виден в публичном каталоге. Окно «Новое» — 30 суток; не путать с датами создания/обновления ETL.
             */
            readonly first_published_at: string | null;
            /** @description Published SKU count on the same Product (family card signal). */
            readonly edition_count: number;
            /** @description Primary published image for catalog cards (sort_order ASC). */
            readonly image: {
                [key: string]: unknown;
            } | null;
            /** @description Hero ТТХ on PDP: fuller set than catalog cards. */
            readonly highlights: {
                [key: string]: string;
            }[];
            /**
             * @description Return description for this SKU edition only (no H1/lead/EAV echo).
             *
             *     Drops bullets that only restate AttributeValue rows already shown in
             *     ТТХ cards / highlights (e.g. «Управление: …», «Вспомогательный…»).
             *     When nothing remains but a hero lead exists, return a light paraphrase
             *     of that lead for the Описание tab (SEO-safe, not an exact duplicate).
             */
            readonly description: string;
            /** @description Short prose blurb for PDP hero (application sentence). */
            readonly lead: string;
            /**
             * @description Характеристики prose — only when there are no structured attrs.
             *
             *     When EAV / category cards cover the ТТХ, return empty to avoid a
             *     duplicate StructuredText block under the cards.
             */
            readonly specs_text: string;
            /** @description Return Аналоги for this SKU edition. */
            readonly analogs_text: string;
            readonly category_name: string;
            readonly category_description: string;
            /** @description Install guide scoped to this SKU edition (all series). */
            readonly category_instructions: string;
            /** @description Optional actuator + bracket picker for ball-valve RFQ. */
            readonly ball_valve_kit: {
                [key: string]: unknown;
            } | null;
            /** @description Adapter ↔ brass 8100 cross-links for PDP («Совместимые позиции»). */
            readonly compatible_positions: {
                [key: string]: unknown;
            }[];
            /** @description Same-product editions for the PDP variant picker (empty if alone). */
            readonly siblings: {
                [key: string]: unknown;
            }[];
            /** @description Unique DN / Kvs / voltage / control values among siblings. */
            readonly variant_axes: {
                [key: string]: string[];
            };
            /** @description ТТХ rows deduped and scoped to the SKU voltage/control variant. */
            readonly attributes: {
                [key: string]: unknown;
            }[];
            /** @description ТТХ grouped for category cards on the Характеристики tab. */
            readonly attribute_groups: {
                [key: string]: unknown;
            }[];
            /** @description Return only published ProductFile rows, ordered. */
            readonly files: {
                [key: string]: unknown;
            }[];
            /** @description Return published gallery images for this edition only. */
            readonly images: {
                [key: string]: unknown;
            }[];
        };
        /** @description SKU card for list: key ТТХ highlights; price gated by SiteSettings. */
        SKUList: {
            readonly id: number;
            /** @description H1/card title: series Product name on family list cards, else edition. */
            readonly name: string;
            /** Сегмент URL */
            readonly slug: string;
            /**
             * Артикул
             * @description Артикул (уникален, не пуст), напр. HVA-5NM или BV215.
             */
            readonly sku_code: string;
            /**
             * Код аналога Belimo
             * @description Код аналога Belimo (для будущей карты аналогов).
             */
            readonly analog_belimo_code: string | null;
            readonly category_slug: string;
            readonly product_slug: string;
            /**
             * Цена
             * Format: decimal
             * @description Цена для КП менеджеру. В публичный API не попадает (см. настройку «показывать цены на сайте»).
             */
            readonly price: string | null;
            /** @description True when prices are hidden (RFQ policy). */
            readonly price_on_request: boolean;
            /** @description True when warehouse quantity is positive (no raw qty in public API). */
            readonly in_stock: boolean;
            /** @description True when first_published_at is within the Новинки window (30 days). */
            readonly is_new: boolean;
            /**
             * Впервые на сайте
             * Format: date-time
             * @description Когда SKU впервые стал виден в публичном каталоге. Окно «Новое» — 30 суток; не путать с датами создания/обновления ETL.
             */
            readonly first_published_at: string | null;
            /** @description Published SKU count on the same Product (family card signal). */
            readonly edition_count: number;
            /** @description Primary published image for catalog cards (sort_order ASC). */
            readonly image: {
                [key: string]: unknown;
            } | null;
            /** @description Compact ТТХ for catalog cards (moment / voltage / control / …). */
            readonly highlights: {
                [key: string]: string;
            }[];
        };
        /** @description Paginated search response (DRF PageNumberPagination shape). */
        SearchResponse: {
            count: number;
            /** Format: uri */
            next: string | null;
            /** Format: uri */
            previous: string | null;
            results: components["schemas"]["SearchResultItem"][];
        };
        /** @description One item in the unified search results list. */
        SearchResultItem: {
            /** @description Тип результата: sku | article | news | page. */
            type: string;
            /** @description Slug (path-сегмент) найденной записи. */
            slug: string;
            /** @description Заголовок (H1) найденной записи. */
            title: string;
            /** @description Канонический path (напр. /<slug>/, /statyi/<slug>/). */
            url: string;
            /** @description Краткое описание (для SKU — lead с PDP; для CMS — начало body). */
            snippet: string;
        };
        /**
         * @description * `new` - Новая
         *     * `in_progress` - В работе
         *     * `done` - Завершена
         * @enum {string}
         */
        StatusEnum: "new" | "in_progress" | "done";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_categories_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    catalog_compare_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_facets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_skus_list: {
        parameters: {
            query?: {
                /** @description ТТХ facet: Аналоги */
                analog?: string;
                /** @description ТТХ facet: Площадь заслонки */
                area?: string;
                /** @description ТТХ facet: Вспомогательный переключатель */
                aux_switch?: string;
                category?: string;
                /** @description ТТХ facet: Совместимый привод */
                compatible_actuators?: string;
                /** @description ТТХ facet: Управление */
                control?: string;
                /** @description ТТХ facet: DN */
                dn?: string;
                /** @description Только товары в наличии (stock_qty > 0). Значения: 1 / true / yes. */
                in_stock?: "1" | "true" | "yes";
                /** @description ТТХ facet: Kvs (м³/ч) */
                kvs?: string;
                /** @description ТТХ facet: Материал корпуса */
                material?: string;
                /** @description ТТХ facet: Крутящий момент */
                moment?: string;
                /** @description Только новинки (first_published_at за последние 30 суток). Порядок: в наличии, затем newer first. Значения: 1 / true / yes. */
                new?: "1" | "true" | "yes";
                /** @description A page number within the paginated result set. */
                page?: number;
                q?: string;
                /** @description ТТХ facet: Термодатчик */
                temp_sensor?: string;
                /** @description ТТХ facet: Напряжение */
                voltage?: string;
                /** @description ТТХ facet: Тип крана */
                ways?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSKUListList"];
                };
            };
        };
    };
    catalog_skus_files_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                sku_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductFileUploadList"];
                };
            };
        };
    };
    catalog_skus_files_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductFileUpload"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductFileUpload"];
                "multipart/form-data": components["schemas"]["ProductFileUpload"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductFileUpload"];
                };
            };
        };
    };
    catalog_skus_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUDetail"];
                };
            };
        };
    };
    content_articles_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedArticleListList"];
                };
            };
        };
    };
    content_articles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
        };
    };
    content_news_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNewsList"];
                };
            };
        };
    };
    content_news_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
        };
    };
    content_pages_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPageList"];
                };
            };
        };
    };
    content_pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    integrations_telegram_webhook_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    leads_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lead"];
                "application/x-www-form-urlencoded": components["schemas"]["Lead"];
                "multipart/form-data": components["schemas"]["Lead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    settings_public_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
