/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/catalog/categories/ — public category list. */
        get: operations["catalog_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/skus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/catalog/skus/ and /api/catalog/skus/{slug}/. */
        get: operations["catalog_skus_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/skus/{sku_slug}/files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET (public) + POST (staff) /api/catalog/skus/{sku_slug}/files/. */
        get: operations["catalog_skus_files_list"];
        put?: never;
        /** @description Upload a PDF to the SKU identified by sku_slug in the URL. */
        post: operations["catalog_skus_files_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/skus/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/catalog/skus/ and /api/catalog/skus/{slug}/. */
        get: operations["catalog_skus_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/articles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/articles/ and /api/content/articles/{slug}/. */
        get: operations["content_articles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/articles/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/articles/ and /api/content/articles/{slug}/. */
        get: operations["content_articles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/news/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/news/ and /api/content/news/{slug}/. */
        get: operations["content_news_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/news/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/news/ and /api/content/news/{slug}/. */
        get: operations["content_news_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/pages/ and /api/content/pages/{slug}/. */
        get: operations["content_pages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/pages/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/content/pages/ and /api/content/pages/{slug}/. */
        get: operations["content_pages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Handle POST: validate, honeypot check, create, schedule email.
         *
         *     Args:
         *         request: DRF request with lead payload.
         *
         *     Returns:
         *         201 with serialized lead (PII-safe: no email/phone in response),
         *         or 201 silent drop if honeypot is filled (no lead created),
         *         or 400 on validation errors.
         */
        post: operations["leads_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Handle GET: parse `q`, run FTS on all three models, return paginated.
         *
         *     Args:
         *         request: DRF request with optional `q` query parameter.
         *
         *     Returns:
         *         200 with paginated results: {count, next, previous, results}.
         *         Each result: {type, slug, title, url}.
         */
        get: operations["search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Expert article (/statyi/<slug>) with cover + excerpt. */
        Article: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            /** @description Краткий анонс для списка /statyi (без HTML). */
            readonly excerpt: string;
            /**
             * Format: uri
             * @description Обложка статьи (локальный MEDIA URL).
             */
            readonly cover: string | null;
            readonly body: string;
            /** @description Видимость в публичном API. */
            readonly is_published: boolean;
            /**
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); null = черновик.
             */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description ТТХ row for SKU detail: slug of Attribute + value + unit. */
        AttributeValue: {
            readonly name: string;
            readonly slug: string;
            readonly unit: string;
            readonly value: string;
        };
        /** @description Public category list/detail fields (series overview + install). */
        Category: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
            /** @description Родительская категория (None для корня дерева). */
            readonly parent: number | null;
            readonly description: string;
            /** @description Общая инструкция по монтажу/управлению для линейки продукции. */
            readonly instructions: string;
            /** @description First published product photo in this category, if any. */
            readonly image: {
                readonly id: number;
                readonly image: string;
                readonly alt?: string;
            } | null;
        };
        /**
         * @description * `datasheet` - Паспорт / datasheet
         *     * `certificate` - Сертификат
         *     * `catalog` - Каталог
         *     * `other` - Прочее
         * @enum {string}
         */
        FileTypeEnum: "datasheet" | "certificate" | "catalog" | "other";
        /**
         * @description Serializer for public Lead creation (RFQ / consultation / replacement).
         *
         *     Only client-facing fields are writable; status/timestamps are read-only.
         *     `email` and `phone` are write-only (PII-safe response). `website` is a
         *     honeypot field — the view silently drops submissions where it's filled.
         */
        Lead: {
            readonly id: number;
            lead_type?: components["schemas"]["LeadTypeEnum"];
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            message: string;
            /** @description SKU, по которому пришла заявка (опц.; SET_NULL при удалении SKU). */
            sku?: number | null;
            /** @description Количество (для RFQ). */
            quantity?: number | null;
            /** @description Код аналога Belimo (для replacement). */
            analog_belimo_code?: string;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /**
             * @description Honeypot — leave empty (hidden from real users).
             * @default
             */
            website: string;
        };
        /**
         * @description * `rfq` - Запрос КП
         *     * `consultation` - Консультация
         *     * `replacement` - Подбор замены
         * @enum {string}
         */
        LeadTypeEnum: "rfq" | "consultation" | "replacement";
        /** @description Company news item (/novosti/<slug>). */
        News: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            readonly body: string;
            /** @description Обложка новости (JPEG/PNG/WebP). */
            readonly cover: string | null;
            /** @description Видимость в публичном API. */
            readonly is_published: boolean;
            /**
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); null = черновик.
             */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Public CMS page (/<slug>). */
        Page: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            readonly body: string;
            /** @description Видимость в публичном API. */
            readonly is_published: boolean;
            /**
             * Format: date-time
             * @description Дата публикации (для сортировки/SEO); null = черновик.
             */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedArticleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Article"][];
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedNewsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["News"][];
        };
        PaginatedPageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Page"][];
        };
        PaginatedProductFileUploadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProductFileUpload"][];
        };
        PaginatedSKUListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SKUList"][];
        };
        /** @description Serializer for staff upload (POST) and public read (GET). */
        ProductFileUpload: {
            readonly id: number;
            title: string;
            /**
             * Format: uri
             * @description Только PDF; лимит и magic bytes — catalog.validators.
             */
            file: string;
            file_type?: components["schemas"]["FileTypeEnum"];
            /** @description Видимость файла в публичном каталоге / PDP. */
            is_published?: boolean;
            /** @description Порядок в блоке «Документы» (меньше = выше). */
            sort_order?: number;
        };
        /** @description SKU PDP payload: list fields + attributes + files. */
        SKUDetail: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
            /** @description Артикул (уникален, не пуст), напр. HVA-5NM или BV215. */
            readonly sku_code: string;
            /** @description Код аналога Belimo (задел для AnalogMap P1). */
            readonly analog_belimo_code: string | null;
            readonly category_slug: string;
            readonly product_slug: string;
            /**
             * Format: decimal
             * @description Цена для КП менеджеру. В публичный API не утекает (см. SiteSettings.show_prices_on_site).
             */
            readonly price: string | null;
            /** @description True when prices are hidden (RFQ policy). */
            readonly price_on_request: boolean;
            readonly description: string;
            readonly specs_text: string;
            readonly analogs_text: string;
            readonly category_name: string;
            readonly category_description: string;
            readonly category_instructions: string;
            readonly attributes: components["schemas"]["AttributeValue"][];
            /** @description Return only published ProductFile rows, ordered. */
            readonly files: {
                [key: string]: unknown;
            }[];
        };
        /** @description SKU card for list: no nested ТТХ; price gated by SiteSettings. */
        SKUList: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
            /** @description Артикул (уникален, не пуст), напр. HVA-5NM или BV215. */
            readonly sku_code: string;
            /** @description Код аналога Belimo (задел для AnalogMap P1). */
            readonly analog_belimo_code: string | null;
            readonly category_slug: string;
            readonly product_slug: string;
            /**
             * Format: decimal
             * @description Цена для КП менеджеру. В публичный API не утекает (см. SiteSettings.show_prices_on_site).
             */
            readonly price: string | null;
            /** @description True when prices are hidden (RFQ policy). */
            readonly price_on_request: boolean;
        };
        /** @description Paginated search response (DRF PageNumberPagination shape). */
        SearchResponse: {
            count: number;
            /** Format: uri */
            next: string | null;
            /** Format: uri */
            previous: string | null;
            results: components["schemas"]["SearchResultItem"][];
        };
        /** @description One item in the unified search results list. */
        SearchResultItem: {
            /** @description Тип результата: sku | article | news. */
            type: string;
            /** @description Slug (path-сегмент) найденной записи. */
            slug: string;
            /** @description Заголовок (H1) найденной записи. */
            title: string;
            /** @description Канонический path (напр. /<slug>/, /statyi/<slug>/). */
            url: string;
        };
        /**
         * @description * `new` - Новая
         *     * `in_progress` - В работе
         *     * `done` - Завершена
         * @enum {string}
         */
        StatusEnum: "new" | "in_progress" | "done";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_categories_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    catalog_skus_list: {
        parameters: {
            query?: {
                category?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSKUListList"];
                };
            };
        };
    };
    catalog_skus_files_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                sku_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductFileUploadList"];
                };
            };
        };
    };
    catalog_skus_files_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductFileUpload"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductFileUpload"];
                "multipart/form-data": components["schemas"]["ProductFileUpload"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductFileUpload"];
                };
            };
        };
    };
    catalog_skus_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUDetail"];
                };
            };
        };
    };
    content_articles_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedArticleList"];
                };
            };
        };
    };
    content_articles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
        };
    };
    content_news_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNewsList"];
                };
            };
        };
    };
    content_news_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
        };
    };
    content_pages_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPageList"];
                };
            };
        };
    };
    content_pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    leads_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lead"];
                "application/x-www-form-urlencoded": components["schemas"]["Lead"];
                "multipart/form-data": components["schemas"]["Lead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
}
