# Generated by Django 6.0.8 on 2026-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True, verbose_name='день')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='уникальные')),
            ],
            options={
                'verbose_name': 'статистика сайта за день',
                'verbose_name_plural': 'статистика сайта по дням',
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='PageDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='день')),
                ('path', models.CharField(db_index=True, max_length=512, verbose_name='путь')),
                ('object_type', models.CharField(choices=[('home', 'Главная'), ('page', 'Страница'), ('sku', 'Артикул'), ('catalog', 'Каталог'), ('article', 'Статья'), ('news', 'Новость'), ('search', 'Поиск'), ('lead', 'Заявка'), ('other', 'Прочее')], db_index=True, default='other', max_length=16, verbose_name='тип')),
                ('object_key', models.CharField(blank=True, default='', help_text='Код артикула, страницы, статьи и т.п.', max_length=255, verbose_name='ключ объекта')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='заголовок')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='уникальные')),
            ],
            options={
                'verbose_name': 'статистика страницы за день',
                'verbose_name_plural': 'статистика страниц по дням',
                'ordering': ('-day', '-views'),
                'indexes': [models.Index(fields=['day', 'object_type', '-views'], name='analytics_page_day_type_views')],
                'constraints': [models.UniqueConstraint(fields=('day', 'path'), name='analytics_pagedailystat_day_path_uniq')],
            },
        ),
    ]
