import type { ComponentType, SVGProps } from "react";

import {
  IconActuator,
  IconAdapter,
  IconAdapterBrM,
  IconAdapterBrMl,
  IconArea03To06,
  IconArea06To10,
  IconArea10To16,
  IconArea16To25,
  IconArea25To40,
  IconAreaOver4,
  IconAreaUpTo03,
  IconAuxSwitch,
  IconAuxSwitchOff,
  IconBallValve,
  IconControlModulating,
  IconControlOnOff,
  IconDamperGate,
  IconDamperRect,
  IconDamperRound,
  IconDn15,
  IconDn20,
  IconDn25,
  IconDn32,
  IconDn40,
  IconDn50,
  IconDn65,
  IconDn80,
  IconDn100,
  IconDn125,
  IconDn150,
  IconElectronicFailsafe,
  IconFailsafe,
  IconFastDamper,
  IconFireDamper,
  IconKit,
  IconKvs6To16,
  IconKvs16To40,
  IconKvs25To6,
  IconKvsOver40,
  IconKvsUpTo25,
  IconPressureHigh,
  IconPressureLow,
  IconPressureMedium,
  IconPressureVeryHigh,
  IconSkipUnknown,
  IconSmokeExtract,
  IconSpringReturn,
  IconTempSensor,
  IconTempSensorOff,
  IconValve2Way,
  IconValve3Way,
  IconVentGeneral,
  IconVoltage24,
  IconVoltage230,
} from "./quizIcons";

type QuizIcon = ComponentType<SVGProps<SVGSVGElement>>;

const CHOICE_ICONS: Record<string, QuizIcon> = {
  actuator: IconActuator,
  ball_valve: IconBallValve,
  kit: IconKit,
  adapter: IconAdapter,
  general: IconVentGeneral,
  fire: IconFireDamper,
  smoke: IconSmokeExtract,
  failsafe: IconFailsafe,
  fast: IconFastDamper,
  spring: IconSpringReturn,
  electronic: IconElectronicFailsafe,
  "smoke_return:spring": IconSpringReturn,
  "smoke_return:no_spring": IconSmokeExtract,
  "24": IconVoltage24,
  "230": IconVoltage230,
  onoff: IconControlOnOff,
  modulating: IconControlModulating,
  up_to_0_3: IconAreaUpTo03,
  "0_3_0_6": IconArea03To06,
  "0_6_1_0": IconArea06To10,
  "1_0_1_6": IconArea10To16,
  "1_6_2_5": IconArea16To25,
  "2_5_4_0": IconArea25To40,
  over_4: IconAreaOver4,
  round: IconDamperRound,
  rectangular: IconDamperRect,
  gate: IconDamperGate,
  low: IconPressureLow,
  medium: IconPressureMedium,
  high: IconPressureHigh,
  very_high: IconPressureVeryHigh,
  "15": IconDn15,
  "20": IconDn20,
  "25": IconDn25,
  "32": IconDn32,
  "40": IconDn40,
  "50": IconDn50,
  "65": IconDn65,
  "80": IconDn80,
  "100": IconDn100,
  "125": IconDn125,
  "150": IconDn150,
  up_to_2_5: IconKvsUpTo25,
  "2_5_to_6": IconKvs25To6,
  "6_to_16": IconKvs6To16,
  "16_to_40": IconKvs16To40,
  over_40: IconKvsOver40,
  "2": IconValve2Way,
  "3": IconValve3Way,
  br_m: IconAdapterBrM,
  br_ml: IconAdapterBrMl,
  skip: IconSkipUnknown,
  "aux_switch:yes": IconAuxSwitch,
  "aux_switch:no": IconAuxSwitchOff,
  "temp_sensor:yes": IconTempSensor,
  "temp_sensor:no": IconTempSensorOff,
};

/** SVG pictogram for a quiz choice card (step-scoped keys beat bare ids). */
export function iconForChoice(
  choiceId: string,
  stepId?: string,
): QuizIcon | null {
  if (stepId) {
    const scoped = CHOICE_ICONS[`${stepId}:${choiceId}`];
    if (scoped) {
      return scoped;
    }
  }
  return CHOICE_ICONS[choiceId] ?? null;
}
