# Generated by Django 6.0.7 on 2026-07-20 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя / контакт')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='телефон')),
                ('company', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='компания')),
                ('notes', models.TextField(blank=True, default='', help_text='Внутренние заметки менеджера (не для клиента).', verbose_name='заметки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_clients', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Заметка'), ('call', 'Звонок'), ('email', 'Письмо'), ('status', 'Смена статуса'), ('other', 'Прочее')], db_index=True, default='note', max_length=20, verbose_name='тип')),
                ('subject', models.CharField(blank=True, default='', max_length=300, verbose_name='тема')),
                ('body', models.TextField(blank=True, default='', verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to='leads.lead', verbose_name='заявка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'активность',
                'verbose_name_plural': 'активности',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Исходящее'), ('inbound', 'Входящее')], db_index=True, default='outbound', max_length=20, verbose_name='направление')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('received', 'Получено')], db_index=True, default='draft', max_length=20, verbose_name='статус')),
                ('to_email', models.EmailField(max_length=254, verbose_name='кому')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='от кого')),
                ('subject', models.CharField(max_length=300, verbose_name='тема')),
                ('body', models.TextField(verbose_name='текст письма')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.client', verbose_name='клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_emails_created', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_emails', to='leads.lead', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'company'], name='crm_client_email_6869d0_idx'),
        ),
    ]
