# Generated by Django 6.0.7 on 2026-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, help_text='Уникальный ключ карточки (нормализуется в нижний регистр).', max_length=254, unique=True, verbose_name='эл. почта'),
        ),
    ]
