# Generated by Django 6.1.1 on 2026-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_client_company_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Запрос реквизитов», «Напоминание о КП».', max_length=200, verbose_name='название')),
                ('subject', models.CharField(blank=True, default='', help_text='Плейсхолдеры {имя}, {компания}, {почта}, {телефон} подставляются автоматически.', max_length=300, verbose_name='тема')),
                ('body', models.TextField(help_text='Плейсхолдеры {имя}, {компания}, {почта}, {телефон} подставляются автоматически.', max_length=20000, verbose_name='текст письма')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'шаблон письма',
                'verbose_name_plural': 'шаблоны писем',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
