# Generated by Django 6.1.1 on 2026-10-06 11:59

import django.db.models.deletion
from django.db import migrations, models

import crm.models


def _ensure_periodic(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    """Upsert IntervalSchedule + PeriodicTask every 2 minutes."""
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=2,
        period="minutes",
    )
    PeriodicTask.objects.update_or_create(
        name="crm.fetch_inbound_email",
        defaults={
            "task": "crm.fetch_inbound_email",
            "interval_id": schedule.pk,
            "crontab_id": None,
            "solar_id": None,
            "clocked_id": None,
            "enabled": True,
            "description": (
                "CRM-mail: IMAP fetch входящих -> EmailMessage(inbound) "
                "-> привязка к Client/Lead (при IMAP_ENABLED=false выходит)."
            ),
        },
    )


def _disable_periodic(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    """Disable the task on reverse (keep row for audit)."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="crm.fetch_inbound_email").update(
        enabled=False,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_email_template"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundMailboxState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("folder", models.CharField(default="INBOX", max_length=100, verbose_name="папка")),
                ("last_uid", models.PositiveBigIntegerField(default=0, verbose_name="последний обработанный UID")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="последний запуск")),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=300, verbose_name="последняя ошибка"),
                ),
            ],
            options={
                "verbose_name": "ящик входящих (IMAP)",
                "verbose_name_plural": "ящик входящих (IMAP)",
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="imap_uid",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="UID в ящике (IMAP)"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="in_reply_to",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="ответ на ID письма"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="message_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Уникальный идентификатор письма (RFC-822): дедупликация и цепочки ответов.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID письма",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="получено (по дате письма)"),
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        storage=crm.models._private_media_storage,
                        upload_to=crm.models.email_attachment_upload_to,
                        verbose_name="файл",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="имя файла")),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="тип содержимого"),
                ),
                ("size", models.PositiveIntegerField(default=0, verbose_name="размер, байт")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="crm.emailmessage",
                        verbose_name="письмо",
                    ),
                ),
            ],
            options={
                "verbose_name": "вложение письма",
                "verbose_name_plural": "вложения писем",
                "ordering": ("created_at",),
            },
        ),
        migrations.RunPython(_ensure_periodic, _disable_periodic),
    ]
