# Generated by Django 6.1.1 on 2026-10-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffmailbox'),
        ('crm', '0007_crm_mail_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='mailbox',
            field=models.ForeignKey(blank=True, help_text='Личный ящик менеджера, через который пришло письмо (пусто — общий ящик).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='accounts.staffmailbox', verbose_name='ящик'),
        ),
    ]
