# Generated by Django 6.1.1 on 2026-10-06 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_sku_first_published_at'),
        ('crm', '0008_emailmessage_mailbox'),
        ('leads', '0009_companymanagerrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', help_text='Проставляется автоматически (КП-<id>).', max_length=30, unique=True, verbose_name='номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Выдано'), ('accepted', 'Согласовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, default='', help_text='Условия КП: сроки, доставка, особые договорённости.', verbose_name='комментарий')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='выдано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.client', verbose_name='клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
                ('lead', models.ForeignKey(blank=True, help_text='Заявка, из которой выдано КП (закрывается при «Выдано»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='leads.lead', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'коммерческое предложение',
                'verbose_name_plural': 'коммерческие предложения',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', help_text='Снимок кода на момент КП (если SKU сняли с публикации).', max_length=100, verbose_name='код артикула')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Необязательно. Цены видны только менеджеру и в счёте.', max_digits=12, null=True, verbose_name='цена за ед., ₽')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.quote', verbose_name='КП')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.sku', verbose_name='артикул (SKU)')),
            ],
            options={
                'verbose_name': 'позиция КП',
                'verbose_name_plural': 'позиции КП',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
