# Generated by Django 6.1.1 on 2026-10-06 17:02

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('accounts', '0010_clientaccount_socialaccount'),
        ('crm', '0009_quote_quoteitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('company_key', models.CharField(db_index=True, editable=False, help_text='Нормализованный ключ совпадения (заполняется автоматически).', max_length=200, unique=True, verbose_name='ключ компании')),
                ('inn', models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='ИНН')),
                ('legal_address', models.CharField(blank=True, default='', max_length=400, verbose_name='юридический адрес')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.OneToOneField(blank=True, help_text='Владелец личного кабинета; v1: один логин = одна карточка (эл. почта = ключ).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_client', to='accounts.clientaccount', verbose_name='аккаунт ЛК'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quote_pdf', 'КП (PDF)'), ('invoice', 'Счёт'), ('spec', 'Спецификация'), ('upd', 'УПД'), ('other', 'Прочее')], db_index=True, default='other', max_length=20, verbose_name='тип')),
                ('file', models.FileField(storage=crm.models._private_media_storage, upload_to=crm.models.client_document_upload_to, verbose_name='файл')),
                ('title', models.CharField(max_length=300, verbose_name='название')),
                ('edo_status', models.CharField(blank=True, choices=[('', '—'), ('sent', 'Отправлен в ЭДО'), ('signed', 'Подписан'), ('rejected', 'Отклонён')], default='', help_text='Ручной статус подписания; API-синк ЭДО — позже.', max_length=20, verbose_name='статус ЭДО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client', verbose_name='клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cabinet.order', verbose_name='заказ')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.quote', verbose_name='КП')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'документ клиента',
                'verbose_name_plural': 'документы клиента',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='company_ref',
            field=models.ForeignKey(blank=True, help_text='Ссылка на карточку компании; текстовое поле «компания» остаётся для маршрутизации.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.company', verbose_name='компания (юрлицо)'),
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Закупщик'), ('engineer', 'Инженер'), ('admin', 'Администратор')], default='buyer', max_length=20, verbose_name='роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_memberships', to='accounts.clientaccount', verbose_name='аккаунт ЛК')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_memberships', to='crm.client', verbose_name='карточка клиента')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'сотрудник компании',
                'verbose_name_plural': 'сотрудники компаний',
                'ordering': ('company', 'id'),
            },
        ),
    ]
