# Generated by Django 6.1.1 on 2026-10-07 13:03

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_phone_digits(apps, schema_editor):
    """Fill Client.phone_digits from the display phone field."""
    import re

    def norm(phone: str) -> str:
        digits = re.sub(r"\D+", "", phone or "")
        if len(digits) == 11 and digits.startswith("8"):
            digits = "7" + digits[1:]
        elif len(digits) == 10:
            digits = "7" + digits
        return digits[:20]

    Client = apps.get_model("crm", "Client")
    for client in Client.objects.exclude(phone="").iterator():
        digits = norm(client.phone)
        if digits and digits != client.phone_digits:
            Client.objects.filter(pk=client.pk).update(phone_digits=digits)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_company_client_account_clientdocument_and_more'),
        ('leads', '0009_companymanagerrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_digits',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Нормализованные цифры — резолв звонков/писем по номеру.', max_length=20, verbose_name='телефон (цифры)'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ID вызова Mango')),
                ('call_id', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='call_id')),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий')], default='inbound', max_length=10, verbose_name='направление')),
                ('state', models.CharField(choices=[('appeared', 'Появился'), ('connected', 'Соединён'), ('disconnected', 'Завершён'), ('on_hold', 'На удержании'), ('transferred', 'Переведён'), ('initiated', 'Инициирован')], default='appeared', max_length=15, verbose_name='состояние')),
                ('from_number', models.CharField(blank=True, default='', max_length=32, verbose_name='откуда')),
                ('to_number', models.CharField(blank=True, default='', max_length=32, verbose_name='куда')),
                ('extension', models.CharField(blank=True, default='', help_text='Внутренний номер менеджера в АТС.', max_length=20, verbose_name='добавочный')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начало')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='соединён')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('talk_duration', models.PositiveIntegerField(default=0, verbose_name='длительность разговора, сек')),
                ('recording_id', models.CharField(blank=True, default='', max_length=200, verbose_name='ID записи Mango')),
                ('recording', models.FileField(blank=True, default='', storage=crm.models._private_media_storage, upload_to=crm.models.call_recording_upload_to, verbose_name='запись разговора')),
                ('last_seq', models.PositiveIntegerField(default=0, help_text='События Mango идут по порядку; устаревшие отбрасываем.', verbose_name='последний seq события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.client', verbose_name='клиент')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='leads.lead', verbose_name='заявка')),
                ('manager', models.ForeignKey(blank=True, help_text='Определяется по добавочному (профиль VPBX на странице пользователя).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'звонок',
                'verbose_name_plural': 'звонки',
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['from_number'], name='crm_call_from_nu_276e9b_idx'), models.Index(fields=['to_number'], name='crm_call_to_numb_31858c_idx'), models.Index(fields=['extension'], name='crm_call_extensi_2c419a_idx')],
            },
        ),
        migrations.RunPython(_backfill_phone_digits, migrations.RunPython.noop),
    ]
