# Generated by Django 6.1.1 on 2026-10-07 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_client_phone_digits_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='ID звонка Mango'),
        ),
        migrations.AlterField(
            model_name='call',
            name='last_seq',
            field=models.PositiveIntegerField(default=0, help_text='События Mango идут по порядку; устаревшие отбрасываем.', verbose_name='№ последнего события'),
        ),
        migrations.AlterField(
            model_name='call',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Определяется по добавочному (профиль АТС на странице пользователя).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='менеджер'),
        ),
    ]
