# Generated by Django 6.1.2 on 2026-10-07 20:17

from decimal import Decimal

from django.db import migrations, models


def _ensure_weekly_report(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    """Upsert Monday 08:00 Europe/Moscow PeriodicTask for the РОП digest."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="8",
        day_of_week="1",
        day_of_month="*",
        month_of_year="*",
        timezone="Europe/Moscow",
    )
    PeriodicTask.objects.update_or_create(
        name="crm.send_weekly_sales_report",
        defaults={
            "task": "crm.send_weekly_sales_report",
            "crontab_id": schedule.pk,
            "interval_id": None,
            "solar_id": None,
            "clocked_id": None,
            "enabled": True,
            "description": (
                "Еженедельный отчёт РОП: воронка менеджеров за 7 дней "
                "на rop_report_email / LEAD_NOTIFY_EMAIL."
            ),
        },
    )


def _disable_weekly_report(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    """Disable the digest on reverse (keep the row)."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="crm.send_weekly_sales_report").update(enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_call_call_id_alter_call_last_seq_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Напоминание менеджеру: просроченные даты видны РОПу в отчёте.', null=True, verbose_name='следующий контакт'),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Пусто при создании — +14 дней от сегодня.', null=True, verbose_name='действует до'),
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), help_text='Ставка НДС в PDF. 0 — не показывать строку НДС.', max_digits=5, verbose_name='НДС, %'),
        ),
        migrations.RunPython(_ensure_weekly_report, _disable_weekly_report),
    ]
