# Generated by Django 6.1.2 on 2026-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0013_client_next_contact_quote_vat_rop_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymember",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Только подтверждённые сотрудники видят ИНН, адрес и состав компании в кабинете. Связь по названию из заявки создаётся неподтверждённой.",
                verbose_name="подтверждён менеджером",
            ),
        ),
    ]
