# Generated by Django 6.0.7 on 2026-07-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(db_index=True, help_text='Старый URL с leading slash, напр. /tproduct/12345-bv215.', max_length=512, unique=True)),
                ('to_path', models.CharField(help_text='Канонический path, напр. /sharovoy-kran-bv215.', max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Moved Permanently'), (302, '302 Found')], default=301, help_text='301 (постоянный, по умолчанию) или 302 (временный).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Можно выключить редирект без удаления записи.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'редирект',
                'verbose_name_plural': 'редиректы',
                'ordering': ('from_path',),
            },
        ),
    ]
