# Generated by Django 6.0.7 on 2026-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='from_path',
            field=models.CharField(db_index=True, help_text='Старый URL с leading slash, напр. /tproduct/12345-bv215.', max_length=512, unique=True, verbose_name='откуда'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Можно выключить редирект без удаления записи.', verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, '301 — постоянно'), (302, '302 — временно')], default=301, help_text='301 (постоянный, по умолчанию) или 302 (временный).', verbose_name='код ответа'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='to_path',
            field=models.CharField(help_text='Канонический path, напр. /sharovoy-kran-bv215.', max_length=512, verbose_name='куда'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
