# Generated by Django 6.0.7 on 2026-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0002_audit_verbose_name_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='from_path',
            field=models.CharField(db_index=True, help_text='Старый URL с ведущим слэшем, напр. /tproduct/12345-bv215.', max_length=512, unique=True, verbose_name='откуда'),
        ),
    ]
