# Generated by Django 6.0.7 on 2026-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0003_admin_russian_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='to_path',
            field=models.CharField(help_text='Канонический путь URL, напр. /sharovoy-kran-bv215.', max_length=512, verbose_name='куда'),
        ),
    ]
