# Generated by Django 6.1.2 on 2026-10-09 11:38

import redirects.pathutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0004_admin_ru_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='from_path',
            field=models.CharField(db_index=True, help_text='Старый URL с ведущим слэшем, напр. /tproduct/12345-bv215.', max_length=512, unique=True, validators=[redirects.pathutils.validate_internal_path], verbose_name='откуда'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='to_path',
            field=models.CharField(help_text='Канонический путь URL, напр. /sharovoy-kran-bv215.', max_length=512, validators=[redirects.pathutils.validate_internal_path], verbose_name='куда'),
        ),
    ]
