# Generated by Django 6.1.2 on 2026-10-09 12:05

from django.db import migrations, models


def lock_disabled_rows(apps, schema_editor):
    """Rows switched off before the flag existed were switched off by a person."""
    Redirect = apps.get_model("redirects", "Redirect")
    Redirect.objects.filter(is_active=False).update(edited_in_admin=True)


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0005_redirect_path_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="edited_in_admin",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Редирект создан или изменён в админке: автоматическое обновление "
                    "редиректов каталога его не перезаписывает и не включает. Снимите "
                    "галочку, чтобы вернуть автообновление."
                ),
                verbose_name="правлено вручную",
            ),
        ),
        migrations.RunPython(lock_disabled_rows, migrations.RunPython.noop),
    ]
