# Generated by Django 6.0.7 on 2026-08-11 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='p256dh')),
                ('auth', models.CharField(max_length=100, verbose_name='auth')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', help_text='Django session key for anonymous support-chat visitors.', max_length=64, verbose_name='session key')),
                ('topic_support', models.BooleanField(default=False, verbose_name='чат поддержки')),
                ('topic_marketing', models.BooleanField(default=False, verbose_name='маркетинг / новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='последняя активность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'push-подписка',
                'verbose_name_plural': 'push-подписки',
                'ordering': ('-last_seen_at',),
            },
        ),
    ]
