# Generated by Django 6.0.8 on 2026-09-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='topic_support',
            field=models.BooleanField(default=False, help_text='Для персонала: заявки и поддержка. Для гостей сайта — чат поддержки.', verbose_name='оповещения Admin (заявки и чат)'),
        ),
    ]
