# Generated by Django 6.0.7 on 2026-08-11 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_admin_russian_labels'),
        ('leads', '0007_admin_ru_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='часовой пояс')),
                ('auto_reply_outside_hours', models.TextField(blank=True, default='Спасибо за сообщение! Сейчас вне рабочего времени — ответим в ближайшие рабочие часы.', verbose_name='автоответ вне часов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
            ],
            options={
                'verbose_name': 'расписание поддержки',
                'verbose_name_plural': 'расписание поддержки',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Сайт'), ('telegram', 'Telegram'), ('vk', 'VK'), ('max', 'MAX')], db_index=True, max_length=16, verbose_name='канал')),
                ('external_user_id', models.CharField(db_index=True, help_text='Telegram chat id, VK user id, или web support_session_id.', max_length=128, verbose_name='внешний id / session')),
                ('display_name', models.CharField(blank=True, default='', max_length=200, verbose_name='имя')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=16, verbose_name='статус')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='последнее сообщение')),
                ('staff_unread_count', models.PositiveIntegerField(default=0, verbose_name='непрочитано (staff)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='crm.client', verbose_name='клиент CRM')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='leads.lead', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'диалог',
                'verbose_name_plural': 'диалоги',
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Клиент'), ('outbound', 'Менеджер'), ('system', 'Система')], db_index=True, max_length=16, verbose_name='направление')),
                ('body', models.TextField(verbose_name='текст')),
                ('external_message_id', models.CharField(blank=True, db_index=True, default='', help_text='Идемпотентность webhook (Telegram message_id и т.п.).', max_length=128, verbose_name='id во внешнем канале')),
                ('outside_hours', models.BooleanField(default=False, verbose_name='вне рабочих часов')),
                ('raw_payload', models.JSONField(blank=True, default=None, null=True, verbose_name='сырой payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='автор (staff)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='supportchat.conversation', verbose_name='диалог')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Пн … 6=Вс', verbose_name='день недели')),
                ('is_closed', models.BooleanField(default=False, verbose_name='выходной')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='supportchat.supportschedule', verbose_name='расписание')),
            ],
            options={
                'verbose_name': 'день расписания',
                'verbose_name_plural': 'дни расписания',
                'ordering': ('weekday',),
            },
        ),
        migrations.CreateModel(
            name='SupportScheduleInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='с')),
                ('end_time', models.TimeField(verbose_name='по')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='supportchat.supportscheduleday', verbose_name='день')),
            ],
            options={
                'verbose_name': 'интервал',
                'verbose_name_plural': 'интервалы',
                'ordering': ('start_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('channel', 'external_user_id'), name='supportchat_conversation_channel_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('conversation', 'external_message_id'), name='supportchat_message_external_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supportscheduleday',
            constraint=models.UniqueConstraint(fields=('schedule', 'weekday'), name='supportchat_schedule_day_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supportscheduleday',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='supportchat_schedule_weekday_range'),
        ),
    ]
