# Generated by Django 6.0.8 on 2026-09-11 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0007_faqitem_consultation_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ('order', 'id'), 'verbose_name': 'вопрос чата', 'verbose_name_plural': 'частые вопросы чата'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='external_user_id',
            field=models.CharField(db_index=True, help_text='Идентификатор в канале: Telegram, VK или сессия виджета на сайте.', max_length=128, verbose_name='внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='staff_unread_count',
            field=models.PositiveIntegerField(default=0, verbose_name='непрочитано менеджером'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='автор (менеджер)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='external_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Для идемпотентности вебхука (идентификатор сообщения Telegram и т.п.).', max_length=128, verbose_name='id во внешнем канале'),
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_payload',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='сырые данные'),
        ),
    ]
