# Generated by Django 6.1.1 on 2026-09-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0010_faqitem_single_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='show_on_home',
            field=models.BooleanField(db_index=True, default=False, help_text='Показывать в секции «Частые вопросы» на главной и в разметке для поисковиков.', verbose_name='блок на главной'),
        ),
    ]
