# Generated by Django 6.1.1 on 2026-10-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0013_faqitem_seed_extended_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='page_url',
            field=models.CharField(blank=True, default='', help_text='Путь страницы, с которой клиент писал последний раз (/catalog/…).', max_length=500, verbose_name='страница сайта'),
        ),
    ]
