# Generated by Django 6.1.1 on 2026-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0014_conversation_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Клиент'), ('outbound', 'Менеджер'), ('system', 'Система'), ('note', 'Заметка')], db_index=True, max_length=16, verbose_name='направление'),
        ),
    ]
