# Generated by Django 6.1.1 on 2026-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0015_alter_message_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='код (/t …)')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('body', models.TextField(verbose_name='текст ответа')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'шаблон ответа',
                'verbose_name_plural': 'шаблоны ответов',
                'ordering': ('order', 'id'),
            },
        ),
    ]
