# Generated by Django 6.1.1 on 2026-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0016_replytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='оценено'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка диалога 1–5, которую поставил клиент.', null=True, verbose_name='оценка клиента'),
        ),
    ]
