# Generated by Django 6.1.1 on 2026-10-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0017_conversation_rated_at_conversation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to='supportchat/attachments/%Y/%m', verbose_name='вложение'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формат вложения'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='имя файла'),
        ),
    ]
