# Generated by Django 6.1.2 on 2026-10-07 19:55

import supportchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0018_message_attachment_message_attachment_mime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, storage=supportchat.models._private_media_storage, upload_to=supportchat.models.support_attachment_upload_to, verbose_name='вложение'),
        ),
    ]
