# Generated by Django 6.1.2 on 2026-10-09 11:07

from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    apps.get_model("supportchat", "Conversation").objects.update(contact_verified=True)


class Migration(migrations.Migration):
    dependencies = [
        ("supportchat", "0019_private_chat_attachments_signed_imap"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="contact_verified",
            field=models.BooleanField(
                default=False,
                help_text="Только такие диалоги видны в кабинете клиента. Ставится само, когда диалог начат из кабинета или менеджер сам привязал клиента.",
                verbose_name="контакт подтверждён",
            ),
        ),
        migrations.RunPython(grandfather_existing, migrations.RunPython.noop),
    ]
