# Generated by Django 6.1.2 on 2026-10-09 11:40

import supportchat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supportchat", "0020_conversation_contact_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportschedule",
            name="timezone",
            field=models.CharField(
                default="Europe/Moscow",
                max_length=64,
                validators=[supportchat.models.validate_timezone_name],
                verbose_name="часовой пояс",
            ),
        ),
    ]
