# Generated by Django 6.1.2 on 2026-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0021_support_schedule_timezone_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pdn_consent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Когда человек отметил согласие в форме на сайте.', null=True, verbose_name='согласие на обработку ПДн'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pdn_policy_version',
            field=models.CharField(blank=True, default='', editable=False, help_text='Редакция политики конфиденциальности на момент согласия.', max_length=32, verbose_name='версия политики ПДн'),
        ),
    ]
