# Generated by Django 6.1.2 on 2026-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0022_pdn_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact_verified',
            field=models.BooleanField(default=False, help_text='Только такие диалоги видны в кабинете клиента. Ставится само, когда диалог начат из кабинета или менеджер сам привязал клиента. Ответ менеджера контакт не подтверждает.', verbose_name='контакт подтверждён'),
        ),
    ]
