# Generated by Django 6.0.7 on 2026-07-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('max', 'MAX')], db_index=True, max_length=20, verbose_name='канал')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('message_preview', models.TextField(blank=True, default='', verbose_name='текст анонса')),
                ('external_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID во внешней системе')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='тип контента')),
            ],
            options={
                'verbose_name': 'анонс в соцсеть',
                'verbose_name_plural': 'анонсы в соцсети',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'channel'], name='social_soci_content_50f358_idx')],
            },
        ),
    ]
