# Generated by Django 6.0.7 on 2026-07-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_sku_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('rfq', 'Запрос КП'), ('consultation', 'Консультация'), ('replacement', 'Подбор замены')], db_index=True, default='rfq', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Количество (для RFQ).', null=True)),
                ('analog_belimo_code', models.CharField(blank=True, default='', help_text='Код аналога Belimo (для replacement).', max_length=100)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(blank=True, help_text='SKU, по которому пришла заявка (опц.; SET_NULL при удалении SKU).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.sku')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ('-created_at',),
            },
        ),
    ]
