# Generated by Django 6.0.7 on 2026-07-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_audit_verbose_name_sync'),
        ('leads', '0004_lead_manager_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='analog_belimo_code',
            field=models.CharField(blank=True, default='', help_text='Код аналога Belimo (для replacement).', max_length=100, verbose_name='код аналога Belimo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('rfq', 'Запрос КП'), ('consultation', 'Консультация'), ('replacement', 'Подбор замены')], db_index=True, default='rfq', max_length=20, verbose_name='тип заявки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Количество (для RFQ).', null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='SKU, по которому пришла заявка (опц.; SET_NULL при удалении SKU).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
