# Generated by Django 6.0.7 on 2026-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_audit_verbose_name_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='эл. почта'),
        ),
    ]
