# Generated by Django 6.0.7 on 2026-07-21 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_admin_ru_help_text'),
        ('leads', '0006_admin_russian_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='analog_belimo_code',
            field=models.CharField(blank=True, default='', help_text='Код аналога Belimo (для заявок на замену).', max_length=100, verbose_name='код аналога Belimo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда заявка была завершена (статус «Завершена»).', null=True, verbose_name='обработано'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Количество позиций в запросе КП (RFQ).', null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда менеджер открыл заявку в админке (стикер считает непросмотренные).', null=True, verbose_name='просмотрено'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Артикул (SKU), по которому пришла заявка (необязательно; при удалении артикула связь обнуляется).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.sku', verbose_name='артикул (SKU)'),
        ),
    ]
