# Generated by Django 6.1.1 on 2026-09-18 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_items_rfq_bundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyManagerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_label', models.CharField(help_text='Название как в заявке; регистр, кавычки и лишние пробелы не важны.', max_length=200, verbose_name='компания')),
                ('company_key', models.CharField(db_index=True, editable=False, help_text='Нормализованный ключ совпадения (заполняется автоматически).', max_length=200, unique=True, verbose_name='ключ компании')),
                ('exclusive', models.BooleanField(default=False, help_text='Убрать менеджера из общей очереди: он получает заявки только по своим компаниям.', verbose_name='только закреплённые компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('assignee', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lead_company_rules', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'закреплённая компания',
                'verbose_name_plural': 'закреплённые компании',
                'ordering': ('company_label',),
            },
        ),
    ]
