# Generated by Django 6.1.2 on 2026-10-09 11:07

from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    apps.get_model("leads", "Lead").objects.update(contact_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_companymanagerrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_verified',
            field=models.BooleanField(default=False, help_text='Новая заявка видна в кабинете клиента, только если контакт подтверждён (ставится само для заявок из кабинета, заведённых менеджером и после отправки КП). Взятая в работу видна всегда. Почту в форме сайта может указать кто угодно.', verbose_name='контакт подтверждён'),
        ),
        migrations.RunPython(grandfather_existing, migrations.RunPython.noop),
    ]
