# Generated by Django 6.1.2 on 2026-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_pdn_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_verified',
            field=models.BooleanField(default=False, help_text='Заявка видна в кабинете клиента, только если контакт подтверждён (ставится само для заявок из кабинета, заведённых менеджером и после отправки КП). Взятие в работу контакт не подтверждает: почту в форме сайта может указать кто угодно.', verbose_name='контакт подтверждён'),
        ),
    ]
